name: Simple Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ${{ secrets.APP_PATH }}
            git config --global --add safe.directory ${{ secrets.APP_PATH }}
            git pull origin main
            npm ci
            npm run build
            npm run prisma:generate
            npx prisma migrate deploy
            pm2 restart ms-backend || pm2 start ecosystem.config.js

